version: '3.9'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "127.0.0.1:${MYSQL_PORT:-0}:3306"
    networks:
      - myapp_network
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails server -b 0.0.0.0
    restart: always
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: mysql2://myuser:mypassword@db/myapp
    depends_on:
      - db
    networks:
      - myapp_network
  nginx:
    image: nginx
    ports:
      - "8080:80"
    environment:
      NGINX_PROXY_PASS: "http://web:3000"
    depends_on:
      - web
    volumes:
      - ./config/nginx:/etc/nginx/conf.d  
    networks:
      - myapp_network
volumes:
  mysql_data:
networks:
  myapp_network:
    driver: bridge

